In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import MetaTrader5 as mt5

# Suppress all warnings
warnings.filterwarnings("ignore")

sns.set_style("darkgrid")

## Importing data from MetaTrader5

In [2]:
if not mt5.initialize(r"c:\Users\Omega Joctan\AppData\Roaming\Pepperstone MetaTrader 5\terminal64.exe"):
    print("Failed to initialize MetaTrader5, error =", mt5.last_error())
    quit()

In [3]:
symbol = "EURUSD"
timeframe = mt5.TIMEFRAME_D1

if not mt5.symbol_select(symbol, True):
    print("Failed to select and add a symbol to the MarketWatch, Error = ",mt5.last_error())
    quit()
    
rates = mt5.copy_rates_from_pos(symbol, timeframe, 1, 10000)
df = pd.DataFrame(rates) # convert rates into a pandas dataframe

df

,time,open,high,low,close,tick_volume,spread,real_volume
0,611280000,1.00780,1.01050,1.00630,1.00760,821,50,0
1,611366400,0.99620,1.00580,0.99100,0.99600,2941,50,0
2,611452800,0.99180,0.99440,0.98760,0.99190,1351,50,0
3,611539200,0.99330,0.99370,0.99310,0.99310,101,50,0
4,611798400,0.97360,0.97360,0.97320,0.97360,81,50,0
...,...,...,...,...,...,...,...,...
9995,1748390400,1.13239,1.13453,1.12838,1.12910,153191,0,0
9996,1748476800,1.12918,1.13849,1.12105,1.13659,191948,0,0
9997,1748563200,1.13630,1.13901,1.13127,1.13470,186924,0,0
9998,1748822400,1.13435,1.14500,1.13412,1.14436,168697,0,0
9999,1748908800,1.14385,1.14549,1.13642,1.13708,147424,0,0

## Creating stationary features

Filter all columns but OHLC

In [4]:
ohlc_df = df.drop(columns=[
    "time",
    "tick_volume",
    "spread",
    "real_volume"
])

ohlc_df

         open     high      low    close
0     1.00780  1.01050  1.00630  1.00760
1     0.99620  1.00580  0.99100  0.99600
2     0.99180  0.99440  0.98760  0.99190
3     0.99330  0.99370  0.99310  0.99310
4     0.97360  0.97360  0.97320  0.97360
...       ...      ...      ...      ...
9995  1.13239  1.13453  1.12838  1.12910
9996  1.12918  1.13849  1.12105  1.13659
9997  1.13630  1.13901  1.13127  1.13470
9998  1.13435  1.14500  1.13412  1.14436
9999  1.14385  1.14549  1.13642  1.13708

[10000 rows x 4 columns]

In [5]:
stationary_df = pd.DataFrame()

for col in ohlc_df.columns:
    stationary_df["diff_"+col] = ohlc_df[col].diff()

stationary_df.dropna(inplace=True)
stationary_df

      diff_open  diff_high  diff_low  diff_close
1      -0.01160   -0.00470  -0.01530    -0.01160
2      -0.00440   -0.01140  -0.00340    -0.00410
3       0.00150   -0.00070   0.00550     0.00120
4      -0.01970   -0.02010  -0.01990    -0.01950
5       0.00070    0.00170   0.00040     0.00090
...         ...        ...       ...         ...
9995   -0.00570   -0.00620  -0.00395    -0.00370
9996   -0.00321    0.00396  -0.00733     0.00749
9997    0.00712    0.00052   0.01022    -0.00189
9998   -0.00195    0.00599   0.00285     0.00966
9999    0.00950    0.00049   0.00230    -0.00728

[9999 rows x 4 columns]

## Check for stationarity

In [6]:
from statsmodels.tsa.stattools import adfuller

for col in stationary_df.columns:
    
    result = adfuller(stationary_df[col])
    print(f'{col} p-value: {result[1]}')

diff_open p-value: 0.0
diff_high p-value: 8.363342845441995e-29
diff_low p-value: 1.2175705509142461e-28
diff_close p-value: 0.0

Checking for correlation

In [7]:
stationary_df.corr()

            diff_open  diff_high  diff_low  diff_close
diff_open    1.000000   0.567907  0.570190    0.019019
diff_high    0.567907   1.000000  0.451576    0.550233
diff_low     0.570190   0.451576  1.000000    0.541775
diff_close   0.019019   0.550233  0.541775    1.000000

In [8]:
print("Mean absolute |p|:", np.abs(np.corrcoef(stationary_df, rowvar=False).mean()))

Mean absolute |p|: 0.5875873892543888

## VAR (Vector Auto Regression)

In [9]:
from statsmodels.tsa.api import VAR

model = VAR(stationary_df)

c:\Anaconda\envs\var-env\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)

In [10]:
# Select optimal lag using AIC
lag_order = model.select_order(maxlags=30)

print(lag_order.summary())

 VAR Order Selection (* highlights the minimums)
==================================================
       AIC         BIC         FPE         HQIC
--------------------------------------------------
0       -41.87      -41.87   6.537e-19      -41.87
1       -45.15      -45.14   2.457e-20      -45.15
2       -45.63      -45.60   1.530e-20      -45.62
3       -45.85      -45.81   1.225e-20      -45.84
4       -45.99      -45.94   1.065e-20      -45.97
5       -46.18      -46.12   8.805e-21      -46.16
6       -46.24      -46.17   8.256e-21      -46.22
7       -46.28      -46.20   7.951e-21      -46.25
8       -46.31      -46.22   7.708e-21      -46.28
9       -46.34      -46.24   7.471e-21      -46.31
10      -46.36      -46.24   7.368e-21      -46.32
11      -46.41      -46.28   6.979e-21      -46.37
12      -46.42      -46.28   6.890e-21      -46.38
13      -46.44      -46.28   6.806e-21      -46.38
14      -46.45      -46.28   6.730e-21      -46.39
15      -46.45      -46.28   6.697e-21      -46.39
16      -46.46      -46.28   6.628e-21      -46.40
17      -46.49     -46.29*   6.460e-21      -46.42
18      -46.50      -46.28   6.419e-21      -46.42
19      -46.50      -46.28   6.383e-21      -46.43
20      -46.50      -46.27   6.358e-21      -46.43
21      -46.51      -46.27   6.306e-21      -46.43
22      -46.52      -46.26   6.292e-21      -46.43
23      -46.53      -46.26   6.216e-21      -46.44
24      -46.53      -46.25   6.185e-21      -46.44
25      -46.54      -46.24   6.162e-21      -46.44
26      -46.54      -46.24   6.113e-21      -46.44
27      -46.55      -46.23   6.092e-21      -46.44
28      -46.55      -46.22   6.086e-21      -46.44
29     -46.56*      -46.22  6.031e-21*     -46.44*
30      -46.56      -46.21   6.033e-21      -46.44
--------------------------------------------------

In [11]:
print(lag_order.aic)

29

In [12]:
# Fit the model with selected lag
results = model.fit(lag_order.aic)

print(results.summary())

  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Fri, 06, Jun, 2025
Time:                     10:42:51
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                   -46.2188
Nobs:                     9970.00    HQIC:                  -46.4425
Log likelihood:           175968.    FPE:                6.03280e-21
AIC:                     -46.5571    Det(Omega_mle):     5.75774e-21
--------------------------------------------------------------------
Results for equation diff_open
=================================================================================
                    coefficient       std. error           t-stat            prob
---------------------------------------------------------------------------------
const                 -0.000002         0.000013           -0.115           0.908
L1.diff_open          -0.959329         0.010918          -87.867           0.000
L1.diff_high           0.009878         0.004957            1.993           0.046
L1.diff_low            0.006869         0.005010            1.371           0.170
L1.diff_close          0.995718         0.004583          217.244           0.000
L2.diff_open          -0.935345         0.015071          -62.062           0.000
L2.diff_high           0.007118         0.006749            1.055           0.292
L2.diff_low            0.022288         0.006819            3.268           0.001
L2.diff_close          0.939861         0.011863           79.226           0.000
L3.diff_open          -0.906595         0.018115          -50.045           0.000
L3.diff_high           0.003072         0.007954            0.386           0.699
L3.diff_low            0.018535         0.008097            2.289           0.022
L3.diff_close          0.910898         0.015703           58.006           0.000
L4.diff_open          -0.898803         0.020501          -43.841           0.000
L4.diff_high           0.003670         0.008912            0.412           0.681
L4.diff_low            0.015668         0.009103            1.721           0.085
L4.diff_close          0.886824         0.018628           47.606           0.000
L5.diff_open          -0.867308         0.022560          -38.445           0.000
L5.diff_high           0.001318         0.009676            0.136           0.892
L5.diff_low           -0.000027         0.009942           -0.003           0.998
L5.diff_close          0.884632         0.020996           42.133           0.000
L6.diff_open          -0.789176         0.024270          -32.516           0.000
L6.diff_high           0.011606         0.010307            1.126           0.260
L6.diff_low            0.013643         0.010623            1.284           0.199
L6.diff_close          0.848155         0.023013           36.856           0.000
L7.diff_open          -0.770098         0.025503          -30.196           0.000
L7.diff_high           0.013242         0.010770            1.230           0.219
L7.diff_low            0.007879         0.011144            0.707           0.480
L7.diff_close          0.770098         0.024664           31.223           0.000
L8.diff_open          -0.730410         0.026546          -27.514           0.000
L8.diff_high           0.008749         0.011166            0.784           0.433
L8.diff_low            0.000966         0.011613            0.083           0.934
L8.diff_close          0.756215         0.025933           29.161           0.000
L9.diff_open          -0.694852         0.027401          -25.358           0.000
L9.diff_high           0.011711         0.011490            1.019           0.308
L9.diff_low           -0.000951         0.012012           -0.079           0.937
L9.diff_close          0.722126         0.026901           26.844           0.000
L10.diff_open         -0.672055         0.028091          -23.924           0.000
L10.diff_high          0.004501         0.011743            0.383           0.701
L10.diff_low          -0.001412         0.012347           -0.114           0.909
L10.diff_close         0.686369         0.027676           24.800           0.000
L11.diff_open         -0.626632         0.028636          -21.883           0.000
L11.diff_high          0.008372         0.011921            0.702           0.482
L11.diff_low           0.001591         0.012607            0.126           0.900
L11.diff_close         0.665435         0.028340           23.481           0.000
L12.diff_open         -0.591270         0.029072          -20.338           0.000
L12.diff_high          0.010100         0.012076            0.836           0.403
L12.diff_low          -0.000565         0.012835           -0.044           0.965
L12.diff_close         0.618549         0.028886           21.414           0.000
L13.diff_open         -0.566562         0.029391          -19.276           0.000
L13.diff_high          0.017391         0.012162            1.430           0.153
L13.diff_low          -0.001794         0.012964           -0.138           0.890
L13.diff_close         0.578490         0.029373           19.694           0.000
L14.diff_open         -0.539181         0.029582          -18.226           0.000
L14.diff_high          0.024354         0.012211            1.995           0.046
L14.diff_low           0.004335         0.013057            0.332           0.740
L14.diff_close         0.541990         0.029707           18.245           0.000
L15.diff_open         -0.528292         0.029599          -17.848           0.000
L15.diff_high          0.017297         0.012226            1.415           0.157
L15.diff_low           0.016641         0.013112            1.269           0.204
L15.diff_close         0.506617         0.029867           16.962           0.000
L16.diff_open         -0.468459         0.029509          -15.875           0.000
L16.diff_high          0.002873         0.012198            0.236           0.814
L16.diff_low           0.014489         0.013085            1.107           0.268
L16.diff_close         0.496871         0.029829           16.658           0.000
L17.diff_open         -0.428873         0.029276          -14.649           0.000
L17.diff_high          0.003347         0.012145            0.276           0.783
L17.diff_low           0.018002         0.013004            1.384           0.166
L17.diff_close         0.445934         0.029691           15.019           0.000
L18.diff_open         -0.388708         0.028782          -13.505           0.000
L18.diff_high          0.006887         0.012045            0.572           0.567
L18.diff_low           0.021002         0.012888            1.630           0.103
L18.diff_close         0.405404         0.029369           13.804           0.000
L19.diff_open         -0.359250         0.028069          -12.799           0.000
L19.diff_high          0.006585         0.011876            0.554           0.579
L19.diff_low           0.015842         0.012675            1.250           0.211
L19.diff_close         0.365912         0.028815           12.699           0.000
L20.diff_open         -0.356987         0.027158          -13.145           0.000
L20.diff_high          0.007326         0.011692            0.627           0.531
L20.diff_low           0.025003         0.012432            2.011           0.044
L20.diff_close         0.333081         0.028113           11.848           0.000
L21.diff_open         -0.290628         0.026168          -11.106           0.000
L21.diff_high          0.014090         0.011438            1.232           0.218
L21.diff_low           0.014675         0.012107            1.212           0.225
L21.diff_close         0.327223         0.027217           12.023           0.000
L22.diff_open         -0.270652         0.024973          -10.838           0.000
L22.diff_high          0.020230         0.011114            1.820           0.069
L22.diff_low           0.011221         0.011710            0.958           0.338
L22.diff_close         0.261915         0.026250            9.978           0.000
L23.diff_open         -0.233271         0.023581           -9.892           0.000
L23.diff_high          0.010534         0.010716            0.983           0.326
L23.diff_low           0.013059         0.011249            1.161           0.246
L23.diff_close         0.241569         0.024993            9.665           0.000
L24.diff_open         -0.205025         0.021954           -9.339           0.000
L24.diff_high          0.005680         0.010249            0.554           0.579
L24.diff_low           0.016769         0.010734            1.562           0.118
L24.diff_close         0.212152         0.023565            9.003           0.000
L25.diff_open         -0.163260         0.020014           -8.157           0.000
L25.diff_high          0.016749         0.009625            1.740           0.082
L25.diff_low           0.013404         0.010041            1.335           0.182
L25.diff_close         0.175517         0.021931            8.003           0.000
L26.diff_open         -0.123194         0.017864           -6.896           0.000
L26.diff_high          0.015609         0.008867            1.760           0.078
L26.diff_low           0.008581         0.009189            0.934           0.350
L26.diff_close         0.134931         0.019817            6.809           0.000
L27.diff_open         -0.076604         0.015135           -5.061           0.000
L27.diff_high          0.010073         0.007938            1.269           0.204
L27.diff_low           0.002902         0.008146            0.356           0.722
L27.diff_close         0.095881         0.017494            5.481           0.000
L28.diff_open         -0.046367         0.011352           -4.085           0.000
L28.diff_high          0.003136         0.006743            0.465           0.642
L28.diff_low           0.005642         0.006836            0.825           0.409
L28.diff_close         0.067361         0.014602            4.613           0.000
L29.diff_open         -0.005922         0.004617           -1.283           0.200
L29.diff_high          0.007026         0.004956            1.418           0.156
L29.diff_low           0.004387         0.005005            0.876           0.381
L29.diff_close         0.035169         0.010568            3.328           0.001
=================================================================================

Results for equation diff_high
=================================================================================
                    coefficient       std. error           t-stat            prob
---------------------------------------------------------------------------------
const                  0.000008         0.000048            0.165           0.869
L1.diff_open          -0.010294         0.038697           -0.266           0.790
L1.diff_high          -0.887555         0.017570          -50.515           0.000
L1.diff_low           -0.020634         0.017757           -1.162           0.245
L1.diff_close          0.969305         0.016245           59.667           0.000
L2.diff_open           0.006028         0.053418            0.113           0.910
L2.diff_high          -0.838250         0.023920          -35.043           0.000
L2.diff_low           -0.057396         0.024169           -2.375           0.018
L2.diff_close          0.914246         0.042047           21.744           0.000
L3.diff_open          -0.160354         0.064208           -2.497           0.013
L3.diff_high          -0.807663         0.028191          -28.650           0.000
L3.diff_low           -0.042960         0.028698           -1.497           0.134
L3.diff_close          0.869460         0.055659           15.621           0.000
L4.diff_open          -0.168775         0.072664           -2.323           0.020
L4.diff_high          -0.785399         0.031589          -24.863           0.000
L4.diff_low           -0.054113         0.032265           -1.677           0.094
L4.diff_close          1.013851         0.066026           15.355           0.000
L5.diff_open          -0.146275         0.079959           -1.829           0.067
L5.diff_high          -0.746785         0.034295          -21.775           0.000
L5.diff_low           -0.098885         0.035238           -2.806           0.005
L5.diff_close          1.012989         0.074419           13.612           0.000
L6.diff_open          -0.084319         0.086023           -0.980           0.327
L6.diff_high          -0.623586         0.036531          -17.070           0.000
L6.diff_low           -0.190235         0.037651           -5.053           0.000
L6.diff_close          0.967369         0.081566           11.860           0.000
L7.diff_open          -0.022933         0.090392           -0.254           0.800
L7.diff_high          -0.606220         0.038172          -15.881           0.000
L7.diff_low           -0.213650         0.039500           -5.409           0.000
L7.diff_close          0.907504         0.087419           10.381           0.000
L8.diff_open           0.036519         0.094090            0.388           0.698
L8.diff_high          -0.633644         0.039576          -16.011           0.000
L8.diff_low           -0.243676         0.041161           -5.920           0.000
L8.diff_close          0.881795         0.091915            9.594           0.000
L9.diff_open           0.164520         0.097121            1.694           0.090
L9.diff_high          -0.621905         0.040726          -15.271           0.000
L9.diff_low           -0.280497         0.042576           -6.588           0.000
L9.diff_close          0.849974         0.095347            8.915           0.000
L10.diff_open          0.159346         0.099565            1.600           0.110
L10.diff_high         -0.594127         0.041620          -14.275           0.000
L10.diff_low          -0.290014         0.043764           -6.627           0.000
L10.diff_close         0.740030         0.098093            7.544           0.000
L11.diff_open          0.124258         0.101496            1.224           0.221
L11.diff_high         -0.586941         0.042253          -13.891           0.000
L11.diff_low          -0.288307         0.044682           -6.452           0.000
L11.diff_close         0.724190         0.100447            7.210           0.000
L12.diff_open          0.118988         0.103043            1.155           0.248
L12.diff_high         -0.515793         0.042801          -12.051           0.000
L12.diff_low          -0.346848         0.045492           -7.624           0.000
L12.diff_close         0.744719         0.102382            7.274           0.000
L13.diff_open          0.158129         0.104175            1.518           0.129
L13.diff_high         -0.535436         0.043106          -12.421           0.000
L13.diff_low          -0.318424         0.045950           -6.930           0.000
L13.diff_close         0.746609         0.104110            7.171           0.000
L14.diff_open          0.138584         0.104851            1.322           0.186
L14.diff_high         -0.526508         0.043279          -12.165           0.000
L14.diff_low          -0.282765         0.046279           -6.110           0.000
L14.diff_close         0.689289         0.105292            6.546           0.000
L15.diff_open          0.134790         0.104909            1.285           0.199
L15.diff_high         -0.527547         0.043332          -12.175           0.000
L15.diff_low          -0.287138         0.046474           -6.179           0.000
L15.diff_close         0.684050         0.105862            6.462           0.000
L16.diff_open          0.163490         0.104590            1.563           0.118
L16.diff_high         -0.534315         0.043235          -12.358           0.000
L16.diff_low          -0.261939         0.046379           -5.648           0.000
L16.diff_close         0.665987         0.105723            6.299           0.000
L17.diff_open          0.139794         0.103766            1.347           0.178
L17.diff_high         -0.461339         0.043047          -10.717           0.000
L17.diff_low          -0.222388         0.046091           -4.825           0.000
L17.diff_close         0.583938         0.105236            5.549           0.000
L18.diff_open          0.121895         0.102015            1.195           0.232
L18.diff_high         -0.408257         0.042693           -9.563           0.000
L18.diff_low          -0.263479         0.045678           -5.768           0.000
L18.diff_close         0.543939         0.104095            5.225           0.000
L19.diff_open          0.076715         0.099486            0.771           0.441
L19.diff_high         -0.418294         0.042095           -9.937           0.000
L19.diff_low          -0.212197         0.044925           -4.723           0.000
L19.diff_close         0.542874         0.102132            5.315           0.000
L20.diff_open          0.044939         0.096257            0.467           0.641
L20.diff_high         -0.397713         0.041441           -9.597           0.000
L20.diff_low          -0.191575         0.044063           -4.348           0.000
L20.diff_close         0.543884         0.099643            5.458           0.000
L21.diff_open         -0.032962         0.092748           -0.355           0.722
L21.diff_high         -0.368731         0.040541           -9.095           0.000
L21.diff_low          -0.150216         0.042910           -3.501           0.000
L21.diff_close         0.508275         0.096468            5.269           0.000
L22.diff_open         -0.089872         0.088514           -1.015           0.310
L22.diff_high         -0.354606         0.039392           -9.002           0.000
L22.diff_low          -0.136622         0.041505           -3.292           0.001
L22.diff_close         0.539944         0.093041            5.803           0.000
L23.diff_open         -0.006998         0.083582           -0.084           0.933
L23.diff_high         -0.345705         0.037983           -9.102           0.000
L23.diff_low          -0.133720         0.039870           -3.354           0.001
L23.diff_close         0.578538         0.088586            6.531           0.000
L24.diff_open         -0.049518         0.077813           -0.636           0.525
L24.diff_high         -0.293787         0.036328           -8.087           0.000
L24.diff_low          -0.153998         0.038044           -4.048           0.000
L24.diff_close         0.478091         0.083523            5.724           0.000
L25.diff_open         -0.019600         0.070936           -0.276           0.782
L25.diff_high         -0.228471         0.034114           -6.697           0.000
L25.diff_low          -0.137770         0.035589           -3.871           0.000
L25.diff_close         0.444997         0.077732            5.725           0.000
L26.diff_open          0.031569         0.063317            0.499           0.618
L26.diff_high         -0.206071         0.031429           -6.557           0.000
L26.diff_low          -0.123982         0.032570           -3.807           0.000
L26.diff_close         0.362280         0.070239            5.158           0.000
L27.diff_open          0.020345         0.053645            0.379           0.705
L27.diff_high         -0.153391         0.028136           -5.452           0.000
L27.diff_low          -0.065690         0.028874           -2.275           0.023
L27.diff_close         0.251005         0.062004            4.048           0.000
L28.diff_open         -0.005863         0.040235           -0.146           0.884
L28.diff_high         -0.087603         0.023901           -3.665           0.000

In [13]:
from statsmodels.stats.stattools import durbin_watson
print(durbin_watson(results.resid))

[2.00297774 2.00197112 1.99923283 2.0005059 ]

## Forecast future values

In [14]:
# Get the last `lag` observations
forecast_input = stationary_df.values[-results.k_ar:]

# Forecast 5 steps ahead
forecast = results.forecast(y=forecast_input, steps=5)

# Convert to DataFrame
forecast_df = pd.DataFrame(forecast, columns=stationary_df.columns)
print(forecast_df)

   diff_open  diff_high  diff_low  diff_close
0  -0.007245  -0.003927 -0.004576   -0.001300
1  -0.001208  -0.001019 -0.001368   -0.000611
2  -0.000666   0.000581 -0.000134   -0.000056
3   0.000106  -0.000553  0.000286   -0.000084
4  -0.000429   0.000045  0.000703    0.001166

In [15]:
def forecast_next(model_res, symbol, timeframe):
    forecast = None
        
    # Get required lags for prediction
    rates = mt5.copy_rates_from_pos(symbol, timeframe, 0, model_res.k_ar+1) # Get rates starting at the current bar to bars=lags used during training
    if rates is None or len(rates) < model_res.k_ar+1:
        print("Failed to get copy rates Error =", mt5.last_error())
        return forecast, None
        
    # Prepare input data and make forecast
    input_data = pd.DataFrame(rates)[["open", "high", "low", "close"]].values
    stationary_input = np.diff(input_data, axis=0)[-model_res.k_ar:] # get the recent values equal to the number of lags used by the model
    
    try:
        forecast = model_res.forecast(stationary_input, steps=1) # predict the next price
    except Exception as e:
        print("Failed to forecast: ", str(e))
        return forecast, None
        
    try:
        updated_data = np.vstack([model_res.endog, stationary_input[-1]]) # concatenate new/last datapoint to the data used during previous training
        updated_model = VAR(updated_data).fit(maxlags=model_res.k_ar) # Retrain the model with new data
    except Exception as e:
        print("Failed to update the model: ", str(e))
        return forecast, None
        
    return forecast, updated_model

In [16]:
res_model = results # Initial model

In [17]:
forecast, res_model = forecast_next(model_res=res_model, symbol=symbol, timeframe=timeframe)

forecast_df = pd.DataFrame(forecast, columns=stationary_df.columns)
print("next forecasted:\n", forecast_df)

next forecasted:
    diff_open  diff_high  diff_low  diff_close
0  -0.001788   0.001743 -0.003324   -0.000326

In [18]:
# mt5.shutdown()